[program:wahaku]
command=/www/wwwroot/wahaku/wahaku-linux
directory=/www/wwwroot/wahaku
autostart=true
autorestart=true
startretries=3
stderr_logfile=/www/wwwroot/wahaku/wahaku.err.log
stdout_logfile=/www/wwwroot/wahaku/wahaku.out.log
environment=AppPort=3000
user=root
priority=999
